// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Local development must read from .env.local only.
import { config } from "dotenv";
config({ path: ".env.local", override: true });
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations require a direct (non-pooled) connection.
    // In production set DIRECT_URL to the non-pooler Neon URL.
    // connect_timeout=30 prevents P1002 when Neon wakes from cold start.
    url: (() => {
      const base = process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"];
      if (!base) return undefined;
      return base.includes("connect_timeout")
        ? base
        : `${base}${base.includes("?") ? "&" : "?"}connect_timeout=30`;
    })(),
  },
});
