// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Load .env.local first (Next.js convention), then .env as fallback
import { config } from "dotenv";
config({ path: ".env.local" });
config({ path: ".env" });
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
