// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Local development must read from .env.local only.
import { config } from "dotenv";
config({ path: ".env.local", override: true });
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations require a direct (non-pooled) connection.
    // In production set DIRECT_URL to the non-pooler Neon URL.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
